
name: Amazon Regression Tests

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run Regression Tests
        run: mvn clean test -Dsurefire.suiteXmlFiles=testng-regression.xml
